#!/bin/bash

# Run `coffee` scripts or a `coffee -i` REPL.
coffee () {
	if (($# == 0)); then
		if has_cmd rlwrap; then
			command rlwrap coffee --interactive
		else
			command coffee --interactive
		fi
	else
		command coffee "$@"
	fi
}
