#!/bin/bash

# Run `coffee` or `coffee -i`, depending on the number of parameters given.
coffee () {
    if (($# == 0)); then
        if has_cmd rlwrap; then
            command rlwrap coffee --interactive
        else
            command coffee --interactive
        fi
    else
        command coffee "$@"
    fi
}
