#!/bin/bash

# Run `node` or `node-repl`, depending on the number of parameters given.
node () {
    if (($# == 0)); then
        if has_cmd rlwrap; then
            command rlwrap node-repl
        else
            command node-repl
        fi
    else
        command node "$@"
    fi
}
