#!/bin/bash

# Run `node` scripts or a `node-repl` REPL.
node () {
	if (($# == 0)); then
		if has_cmd rlwrap; then
			command rlwrap node-repl
		else
			command node-repl
		fi
	else
		command node "$@"
	fi
}
