#!/bin/bash

# Ensure that the given command is available.
# Usage: require_cmd COMMAND
require_cmd () {
	if ! has_cmd "$1"; then
		echo "$(basename -- "$0"): command not found: $1" >&2
		shift
		if (($# != 0)); then
			echo "$@" >&2
		fi
		return 1
	fi
}
