#!/bin/bash
#
# bash_logout
# bash-specific logout script

# Clear ttys
if type tty >/dev/null 2>&1 ; then
    case "$(tty)" in
        /dev/tty[0-9]*) clear ;;
    esac
fi

# Load local overrides
source_maybe "$HOME/.bash_logout_local"
