#!/bin/bash
#
# bash_prompt
# bash-specific prompting

# Helper functions
function __vc_prompt () {
	has_cmd vcprompt || return
	if [[ -d '.svn' ]]; then
		vcprompt -f ' [%n:%r]'
	else
		vcprompt -f ' [%n:%b]'
	fi
}
function __pwd_with_tilde () {
	/usr/bin/sed -E "s|^$HOME|~|" <<<"$PWD"
}
function __pwd_with_tilde_abbr () {
	__pwd_with_tilde | /usr/bin/sed -E 's|^(.+)(.{27})$|...\2|'
}

# Colours
PS_CLEAR="\[\033[0m\]"
PS_BLUE="\[\033[34m\]"
PS_MAGENTA="\[\033[35m\]"

# Helper definitions
PS_ARROW=">"
case "$TERM" in
xterm*|screen*) PS_ARROW="»" ;;
esac
PS_WINDOW=""
if [[ -n "$WINDOW" ]]; then
	PS_WINDOW='#$WINDOW:'
fi
PS_SHLVL=""
if (($SHLVL > 1)); then
	PS_SHLVL='[$SHLVL]'
fi
PS_PWD='$(__pwd_with_tilde_abbr)'
PS_VCS='$(__vc_prompt)'

# Set the prompt
PS1="${PS_BLUE}${PS_PWD}${PS_MAGENTA}${PS_VCS}${PS_CLEAR} ${PS_SHLVL}${PS_ARROW} "

# Set terminal titles
function __term_func () {
	title "$is" "$USER@${HOSTNAME%.*}" "$(__pwd_with_tilde_abbr)"
}

PROMPT_COMMAND='__term_func'
