#!/bin/bash
#
# bashrc
# bash-specific interactive settings
shopt -s nullglob

# Don't configure a non-interactive shell
test -n "$PS1" || return

# Don't recurse
test -z "$SH_RC_DONE" || return
SH_RC_DONE=t

# Load login/environment settings
if [[ -e "$HOME/.bash_profile" ]]; then
    source "$HOME/.bash_profile"
fi

# System-wide bashrc
if [[ -e "/etc/bashrc" ]]; then
    source "/etc/bashrc"
fi

# Load common settings
source_all "$HOME/.sh.d"

# Load options
source_maybe "$HOME/.bash_options"

# Load prompting
source_maybe "$HOME/.bash_prompt"

# Load aliases
source_all "$HOME/.alias.d"

# Load advanced completion
if [[ "$TERM_PROGRAM" != "DTerm" ]]; then
	source_maybe "$HOME/.bash_completion_link"
fi

# Augment PATH
munge PATH "$HOME/bin" before
# munge PATH . after

# Load local overrides
source_maybe "$HOME/.bashrc_local"
