#!/bin/bash
#
# bash_profile
# bash-specific login/environment settings
shopt -s nullglob

# We're running the Bourne Again Shell
is=bash

# Don't recurse
test -z "$SH_ENV_DONE" || return
SH_ENV_DONE=t

# System-wide profile
if [[ -e "/etc/bash_profile" ]]; then
	source "/etc/bash_profile"
elif [[ -e "/etc/profile" ]]; then
	source "/etc/profile"
fi

# Remap <Caps-Lock> on ttys
if uname | egrep -q "Linux" && type tty >/dev/null 2>&1 ; then
	case "$(tty)" in
	/dev/tty[0-9]*)
		dumpkeys | perl -pe 's/\bCaps_Lock\b/Control/' | loadkeys --quiet -
		;;
	esac
fi

# Set up autoloading
FPATH="$HOME/lib/bash:$HOME/.bash.d:$HOME/.fpath.d"
if [[ -e "$HOME/.bash_autoload" ]]; then
	# Load the autoload function
	source "$HOME/.bash_autoload"
	# Autoload shell functions from all executable files in bash.d.
	# The executable bit is not necessary, but gives you an easy way to
	# stop the autoloading of a particular shell function.
	autoload $(find -H ~/.bash.d ~/.fpath.d -type f -perm -0111 | xargs basename)
fi

# Load environment settings
source_all "$HOME/.env.d"

# Load local overrides
source_maybe "$HOME/.bash_profile_local"

# Load interactive settings
source_maybe "$HOME/.bashrc"
