#!/bin/bash
#
# bash_prompt
# bash-specific prompting

# Helper functions
__parse_git_dirty () {
    git status 2> /dev/null | tail -n1 | egrep -q '^nothing to commit \(working directory clean\)$' || echo '*'
}
__pwd_with_tilde () {
    echo $PWD | sed -e "s:$HOME:~:"
}

# Set the prompt
PS1='\h:\W$(__git_ps1 "[%s$(__parse_git_dirty)]") \u> '


# Set terminal titles
PROMPT_COMMAND='print_term_title "${HOSTNAME%%.*}:$(basename "$(__pwd_with_tilde)")$(__git_ps1 "[%s$(__parse_git_dirty)]") $USER"'
