#!/bin/zsh
#
# zsh_prompt
# zsh-specific prompting
autoload -U promptinit
promptinit

# Helper definitions
PS_ARROW=">"
PS_DIRTY="*"
PS_FAIL="!"
PS_WINDOW=""
# if [[ -n "$WINDOW" ]]; then
#     PS_WINDOW="#$WINDOW:"
# fi

# Set the prompt
PROMPT="%B%(?..[%?] )%b$PS_ARROW "
RPROMPT="%{$fg_no_bold[blue]%}%55<...<%~%{$reset_color%}"
if [[ -n "$SSH_CLIENT" ]]; then
    RPROMPT="$RPROMPT|%n@%m"
fi

# Set the title
precmd () {
    title "$is" "%n@%m" "%55<...<%~"
}

# Set the title for external commands
preexec () {
    title "$1" "%n@%m" "%35<...<%~"
}
