#!/bin/zsh
#
# zsh_completion
# zsh-specific programmable completion
autoload -U compinit
compinit

# Bash compatibility
autoload -U bashcompinit
bashcompinit

# Colorful listings
zstyle ':completion:*' list-colors $LS_COLORS

# Sake task completion
__sake_task_list () {
	reply=($(sake -T | awk '{ print $2 }'))
}
# I should really learn how to use compdef here...
compctl -K __sake_task_list sake

# GitHub command completion
# compctl -k "($(github help | perl -ne 'print if s/^\s+(\S+)\s+=>.*$/$1/'))" github gh

# Command completion via tabtab:
source_maybe ~/.tabtab.zsh
