#!/bin/zsh
#
# zsh_completion
# zsh-specific programmable completion
# The following lines were added by compinstall

zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' '+m:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/Users/mkhl/.zsh_completion'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Ignored extensions
fignore=(DS_Store $fignore)

# Colorful listings
zstyle ':completion:*' list-colors $LS_COLORS

# Command completion via tabtab:
source_maybe ~/.tabtab.zsh
