#!/bin/zsh
#
# zsh_completion
# zsh-specific programmable completion
autoload -Uz compinit
compinit

# Ignored extensions
fignore=(DS_Store $fignore)

# Colorful listings
zstyle ':completion:*' list-colors $LS_COLORS

# Command completion via tabtab:
source_maybe ~/.tabtab.zsh
