#!/bin/zsh
#
# zsh_prompt
# zsh-specific prompting
autoload -Uz promptinit
promptinit
colors

# Helper definitions
PS_ARROW=">"
PS_WINDOW=""
if [[ -n "$WINDOW" ]]; then
	PS_WINDOW='#$WINDOW:'
fi

# VCS information
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable svn git bzr darcs hg;
zstyle ':vcs_info:*' actionformats "[%s/%b|%a]";
zstyle ':vcs_info:*' formats       "[%s/%b]";

# Set the prompt
PROMPT='%B%(?..[%?] )%b$is$PS_ARROW '
RPROMPT='%{${fg_no_bold[blue]}%}%55<...<%~${vcs_info_msg_0_}%{${reset_color}%}'
if [[ -n "$SSH_CLIENT" ]]; then
	RPROMPT="$RPROMPT|%n@%m"
fi

# Set the title
precmd () {
	vcs_info
	title "$is" "%n@%m" "%55<...<%~"
}

# Set the title for external commands
preexec () {
	title "$1" "%n@%m" "%35<...<%~"
}
