" -*- mode: text -*-

" List of fonts which will be used for the GUI version of Vim.
if has("gui_macvim")
    set guifont=Menlo\ Regular:h11,Monaco:h11
endif

" Disable cursor blinking in normal mode.
set guicursor=n:blinkon0

" Disable the toolbar.
set guioptions-=T

" Number of lines of the Vim window.
set lines=40

" vim: ft=vim
