" -*- mode: text -*-

" Features: Vim. Backspace.
set nocompatible
set backspace=indent,eol,start

" Editor: Ruler. Title. Visual bell. Menu completion.
set ruler title visualbell wildmenu

" Searching: Incremental w/o wrapping. Highlighting. Case folding.
set incsearch nowrapscan
set showmatch hlsearch
set smartcase ignorecase

" Indentation: 4 spaces. No tabs. Smart.
set tabstop=4  shiftwidth=4
set expandtab  smarttab
set autoindent smartindent

" Features: Syntax. File type detection.
syntax on
filetype plugin indent on

" Keyword Lookup: Support Perl, Python, Ruby.
autocmd FileType perl   setlocal keywordprg=perldoc
autocmd FileType python setlocal keywordprg=pydoc
autocmd FileType ruby   setlocal keywordprg=ri

" Define a Leader.
let mapleader = ","

" Disable cursor keys in insert mode.
inoremap <Left>  <NOP>
inoremap <Right> <NOP>
inoremap <Up>    <NOP>
inoremap <Down>  <NOP>

" Don't use ex(1) mode, use Q for formatting.
noremap Q gq
" This is not vi-compatible but much more logical.
noremap Y y$
" Avoid typos and be more compatible with ed(1).
command! Q  q!
command! W  w!
command! E  e!
command! Wq wq
command! WQ wq

" Use <Ctrl-h/j/k/l> for motion.
noremap <C-h> ^
noremap <C-j> }
noremap <C-k> {
noremap <C-l> $

" Fold and Unfold with the <tab>-key
nnoremap <Tab> za

" Some emacs(1) style keybindings.
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-B> <Left>
cnoremap <C-F> <Right>
cnoremap <C-D> <Del>

" Disable current highlighting.
nmap <silent> <C-n> :nohlsearch<CR>

" vim: ft=vim
