#!/bin/bash

# Open Rubygems documentation in a browser.
# Note: This version assumes Mac OS X.
# Usage: gemdoc GEM
# From http://stephencelis.com/archive/2008/6/bashfully-yours-gem-shortcuts
gemdoc () {
    local gemdir="$(gem env gemdir)"
    open "$gemdir/doc/$(ls "$gemdir/doc/" | grep $1 | sort | tail -n1)/rdoc/index.html"
}
