#!/bin/bash

# Begin titlebar text
__term_title_begin () {
    case "$TERM" in
        dumb|linux|sun|emacs)
            ;;
        screen)
            echo -n "\e_"
            ;;
        sun-cmd)
            echo -n "\e]l"
            #echo -n "\e]L"
            ;;
        ansi|dtterm|eterm|Eterm|iris-ansi|rxvt*|screen-w|xterm*|*xterm)
            echo -n "\e]2;"
            ;;
        *)
            ;;
    esac
}

# End titlebar text
__term_title_end () {
    case "$TERM" in
        dumb|linux|sun|emacs)
            ;;
        screen)
            echo -n "\e\\"
            ;;
        sun-cmd)
            echo -n "\e\\"
            ;;
        ansi|dtterm|eterm|Eterm|iris-ansi|rxvt*|screen-w|xterm*|*xterm)
            echo -n "\a"
            ;;
        *)
            ;;
    esac
}

# Display titlebar text
if has_titlebar ; then
    print_term_title () {
        echo -ne "$(__term_title_begin)$@$(__term_title_end)"
    }
else
    print_term_title () {
        true
    }
fi
