#!/bin/bash

# Load all source files from the given directories into the running shell.
# Usage: source_all [DIR ...]
source_all () {
	shopt -q nullglob
	local old_nullglob=$?
	shopt -s nullglob
	for dir; do
		if [[ -d "$dir" ]]; then
			for file in "$dir"/*.sh "$dir"/*.$is; do
				source "$file"
			done
		fi
	done
	if (( $old_nullglob != 0 )); then
		shopt -u nullglob
	fi
}
