#!/bin/bash

# Load all source files from the given directories.
# Usage: source_all [DIR ...]
source_all () {
	local dir
	local file
	for dir; do
		if [[ -d "$dir" ]]; then
			for file in $(command ls "$dir"); do
				case "$file" in
				*.sh|*.$is)
					source "$dir/$file"
					;;
				esac
			done
		fi
	done
}
