#!/bin/zsh

# Display title
title () {
    if has_title ; then
        # Escape '%' chars in $1, make nonprintables visible.
        local cmd=${(V)1//\%/\%\%}
        # Truncate command, and join lines.
        cmd=$(print -Pn "%40>...>$cmd" | tr -d "\n")
        case "$TERM" in
        screen*)
            print -Pn "${PROMPT_TS}$cmd:$3${PROMPT_FS}"
            ;;
        *)
            print -Pn "${PROMPT_TS}$2 | $cmd:$3${PROMPT_FS}"
            ;;
        esac
    fi
}
